source 'https://rubygems.org'

ruby '4.0.6'

gem 'sinatra', '~> 4.2', require: 'sinatra/base'
gem 'puma', '~> 8.0'
gem 'rack-cors', '~> 3.0', require: 'rack/cors'
gem 'rack-session', '~> 2.1', require: 'rack/session'

gem 'activerecord', '~> 8.1', require: 'active_record'
gem 'pg', '~> 1.6'

gem 'bcrypt', '~> 3.1'
gem 'nokogiri', '~> 1.19'

gem 'rake', '~> 13.0'
